# HMM validation (grasp vs. non-grasp)

Dieses Notebook trainiert 10 HMM-Modelle (n_states=3..12) auf den Trainings-CSV-Dateien, führt pro Modell auto_grasp_state aus und validiert anschließend gegen val_csv mit der Ground-Truth-Spalte aktion (0/1).

Harte Qualitätsgrenze: precision_grasp_micro >= 0.90.

Begründung für diese Grenze: Greif-Vorhersagen sollen verlässlich sein und zu viele False Positives vermeiden.

Zweites Ranking-Kriterium unter den zulässigen Modellen: recall_grasp_micro.

Interpretation: recall_grasp = TP / (TP + FN) beantwortet die Frage: „Wie viele echte Greif-Frames werden erkannt?“

Tie-Breaker: f1_grasp_micro, balanced_accuracy_micro, mcc_micro.

Reporting-Strategie: Alle Metriken bleiben sichtbar, um sowohl False Positives als auch verpasste Greif-Frames zu überwachen.

In [1]:
from __future__ import annotations

import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
)

from handpose.config_loader import ROOT_DIR, get_settings
from handpose.backend.ML.HMM.features_hmm import HmmFeatureExtractor
from handpose.backend.ML.HMM.model_hmm import HmmWrapper
from handpose.backend.ML.DBSCAN.auto_grasp_state import detect_grasp_state_by_mean_max_reach_y

/Users/jole/Library/Caches/pypoetry/virtualenvs/handpose-estimation-ZvAsxI9K-py3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Paths
training_dir_preferred = ROOT_DIR / "data/03_processed/features/training"
training_dir_fallback = ROOT_DIR / "data/03_processed/keypoints/training"
validation_dir = ROOT_DIR / "data/05_validation/val_csv"

settings = get_settings()
HMM_N_ITER = settings.hmm.n_iter
HMM_RANDOM_STATE = settings.hmm.random_state
FEATURE_INDEX_MAX_REACH_Y = settings.dbscan.feature_index_max_reach_y
MIN_PRECISION_GRASP_MICRO = 0.90
SECONDARY_VALIDATION_METRIC = "recall_grasp_micro"
PRIMARY_VALIDATION_METRIC = SECONDARY_VALIDATION_METRIC
RANKING_COLUMNS = [
    "validation_score",
    "f1_grasp_micro",
    "balanced_accuracy_micro",
    "mcc_micro",
]
RANKING_ASCENDING = [False] * len(RANKING_COLUMNS)

STATE_RANGE = range(3, 13)

print(f'ROOT_DIR: {ROOT_DIR}')
print(f'Preferred training dir: {training_dir_preferred}')
print(f'Fallback training dir: {training_dir_fallback}')
print(f'Validation dir: {validation_dir}')

ROOT_DIR: /Users/jole/Studium/HandPose/HandPoseEstimation
Preferred training dir: /Users/jole/Studium/HandPose/HandPoseEstimation/data/03_processed/features/training
Fallback training dir: /Users/jole/Studium/HandPose/HandPoseEstimation/data/03_processed/keypoints/training
Validation dir: /Users/jole/Studium/HandPose/HandPoseEstimation/data/05_validation/val_csv

In [3]:
REQUIRED_KEYPOINT_COLS = {"l_x_8", "l_y_8", "r_x_8", "r_y_8", "l_x_4", "l_y_4", "r_x_4", "r_y_4"}


def has_required_keypoint_columns(csv_path: Path) -> bool:
    sample = pd.read_csv(csv_path, sep=";", nrows=1)
    return REQUIRED_KEYPOINT_COLS.issubset(set(sample.columns))


def resolve_training_dir(preferred_dir: Path, fallback_dir: Path) -> Path:
    preferred_files = sorted(preferred_dir.glob("*.csv"))
    if preferred_files and has_required_keypoint_columns(preferred_files[0]):
        return preferred_dir

    fallback_files = sorted(fallback_dir.glob("*.csv"))
    if fallback_files and has_required_keypoint_columns(fallback_files[0]):
        print(
            "INFO: Preferred training dir has no raw keypoint columns required by HmmFeatureExtractor."
        )
        print(f"Using fallback dir for HMM training: {fallback_dir}")
        return fallback_dir

    raise ValueError(
        "No usable training directory found. Neither preferred nor fallback has required keypoint columns."
    )


def extract_action_labels(df: pd.DataFrame) -> np.ndarray:
    for col in ["aktion", "Aktion", "action", "Action"]:
        if col in df.columns:
            y = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int).to_numpy()
            return (y > 0).astype(int)
    raise KeyError("No action column found. Expected one of: aktion, Aktion, action, Action")


def compute_binary_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict[str, float]:
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    unique_true = np.unique(y_true)
    unique_pred = np.unique(y_pred)

    if len(unique_true) > 1:
        bal_acc = float(balanced_accuracy_score(y_true, y_pred))
    else:
        bal_acc = float("nan")

    if len(unique_true) > 1 and len(unique_pred) > 1:
        mcc = float(matthews_corrcoef(y_true, y_pred))
    else:
        mcc = 0.0

    specificity = tn / (tn + fp) if (tn + fp) > 0 else float("nan")

    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "balanced_accuracy": bal_acc,
        "precision_grasp": float(precision_score(y_true, y_pred, pos_label=1, zero_division=0)),
        "recall_grasp": float(recall_score(y_true, y_pred, pos_label=1, zero_division=0)),
        "f1_grasp": float(f1_score(y_true, y_pred, pos_label=1, zero_division=0)),
        "specificity_non_grasp": float(specificity),
        "mcc": mcc,
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }

In [4]:
# Load training data and precompute HMM feature sequences
extractor = HmmFeatureExtractor()
training_dir = resolve_training_dir(training_dir_preferred, training_dir_fallback)
training_files = sorted(training_dir.glob("*.csv"))
validation_files = sorted(validation_dir.glob("*.csv"))

if not training_files:
    raise FileNotFoundError(f"No training CSV files found in {training_dir}")
if not validation_files:
    raise FileNotFoundError(f"No validation CSV files found in {validation_dir}")

X_train_parts: list[np.ndarray] = []
train_lengths: list[int] = []

for csv_path in training_files:
    df = extractor.process_csv(csv_path)
    if df is None:
        continue

    X_seq, _ = extractor.calculate_features(df)
    if len(X_seq) == 0:
        continue

    X_train_parts.append(X_seq)
    train_lengths.append(len(X_seq))

if not X_train_parts:
    raise RuntimeError("Could not extract any training features.")

X_train_concat = np.concatenate(X_train_parts, axis=0)

validation_data = []
for csv_path in validation_files:
    df_val = extractor.process_csv(csv_path)
    if df_val is None:
        continue

    X_val, _ = extractor.calculate_features(df_val)
    y_true = extract_action_labels(df_val)

    seq_len = min(len(X_val), len(y_true))
    if seq_len == 0:
        continue

    validation_data.append({
        "file_name": csv_path.name,
        "X": X_val[:seq_len],
        "y_true": y_true[:seq_len],
    })

if not validation_data:
    raise RuntimeError("No usable validation data loaded.")

print(f"Training directory used: {training_dir}")
print(f"Training files loaded: {len(train_lengths)}")
print(f"Validation files loaded: {len(validation_data)}")
print(f"Training frames total: {len(X_train_concat)}")

INFO: Preferred training dir has no raw keypoint columns required by HmmFeatureExtractor.
Using fallback dir for HMM training: /Users/jole/Studium/HandPose/HandPoseEstimation/data/03_processed/keypoints/training
Training directory used: /Users/jole/Studium/HandPose/HandPoseEstimation/data/03_processed/keypoints/training
Training files loaded: 501
Validation files loaded: 7
Training frames total: 119658

/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")
/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")
/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")
/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")
/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")
/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")
/Users/jole/Studium/HandPose/HandPoseEstimation/src/handpose/backend/ML/HMM/features_hmm.py:33: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method="linear", limit_direction="both")

In [5]:
# Train and evaluate models for n_states = 3..12
per_file_rows: list[dict] = []
model_rows: list[dict] = []

for n_states in STATE_RANGE:
    print(f"\n=== Training HMM with n_states={n_states} ===")

    wrapper = HmmWrapper(
        n_states=n_states,
        n_iter=HMM_N_ITER,
        random_state=HMM_RANDOM_STATE,
    )
    wrapper.train(X_train_concat, train_lengths)

    with tempfile.TemporaryDirectory(prefix=f"hmm_states_{n_states}_") as tmp_dir_str:
        tmp_dir = Path(tmp_dir_str)
        model_path = tmp_dir / "hmm_model.pkl"
        scaler_path = tmp_dir / "scaler.pkl"
        wrapper.save(str(model_path), str(scaler_path))

        grasp_state, state_means, files_used_for_grasp = detect_grasp_state_by_mean_max_reach_y(
            raw_data_dir=training_dir,
            hmm_model_dir=tmp_dir,
            feature_index_max_reach_y=FEATURE_INDEX_MAX_REACH_Y,
        )

    if grasp_state is None:
        print(f"WARN: Could not detect grasp_state for n_states={n_states}. Skipping evaluation.")
        continue

    y_true_all: list[np.ndarray] = []
    y_pred_all: list[np.ndarray] = []

    for item in validation_data:
        states = wrapper.predict(item["X"])
        y_pred = (states == grasp_state).astype(int)
        y_true = item["y_true"]

        seq_len = min(len(y_true), len(y_pred))
        y_true_eval = y_true[:seq_len]
        y_pred_eval = y_pred[:seq_len]

        metrics = compute_binary_metrics(y_true_eval, y_pred_eval)
        metrics.update({
            "n_states": n_states,
            "grasp_state": int(grasp_state),
            "file_name": item["file_name"],
            "n_frames": int(seq_len),
            "files_used_for_grasp_detection": int(files_used_for_grasp),
            "state_means": str(state_means),
        })
        per_file_rows.append(metrics)

        y_true_all.append(y_true_eval)
        y_pred_all.append(y_pred_eval)

    y_true_all_concat = np.concatenate(y_true_all, axis=0)
    y_pred_all_concat = np.concatenate(y_pred_all, axis=0)

    micro = compute_binary_metrics(y_true_all_concat, y_pred_all_concat)

    per_model_df = pd.DataFrame([r for r in per_file_rows if r["n_states"] == n_states])
    macro_f1 = float(per_model_df["f1_grasp"].mean())
    macro_bal_acc = float(per_model_df["balanced_accuracy"].mean())

    model_rows.append({
        "n_states": n_states,
        "grasp_state": int(grasp_state),
        "files_used_for_grasp_detection": int(files_used_for_grasp),
        "n_frames_total": int(len(y_true_all_concat)),
        "accuracy_micro": micro["accuracy"],
        "balanced_accuracy_micro": micro["balanced_accuracy"],
        "precision_grasp_micro": micro["precision_grasp"],
        "recall_grasp_micro": micro["recall_grasp"],
        "f1_grasp_micro": micro["f1_grasp"],
        "specificity_non_grasp_micro": micro["specificity_non_grasp"],
        "mcc_micro": micro["mcc"],
        "tn_micro": micro["tn"],
        "fp_micro": micro["fp"],
        "fn_micro": micro["fn"],
        "tp_micro": micro["tp"],
        "f1_grasp_macro": macro_f1,
        "balanced_accuracy_macro": macro_bal_acc,
        # Primary validation score: maximize grasp recall (class 1)
        "validation_score": micro["recall_grasp"],
        "validation_score_name": PRIMARY_VALIDATION_METRIC,
    })

=== Training HMM with n_states=3 ===

         1 -676820.82275636             +nan
         2 -457562.66301470 +219258.15974166
         3 -445284.55224460  +12278.11077010
         4 -443924.24689086   +1360.30535374
         5 -443693.02224269    +231.22464817
         6 -443647.21414095     +45.80810174
         7 -443637.51665651      +9.69748445
         8 -443635.09757567      +2.41908083
         9 -443634.19744030      +0.90013537
        10 -443633.63335927      +0.56408103
        11 -443633.14355059      +0.48980868
        12 -443632.66089277      +0.48265782
        13 -443632.16203612      +0.49885664
        14 -443631.63404080      +0.52799532
        15 -443631.06614189      +0.56789891
        16 -443630.44725534      +0.61888655
        17 -443629.76497829      +0.68227705
        18 -443629.00509764      +0.75988064
        19 -443628.15133031      +0.85376734
        20 -443627.18510962      +0.96622069
        21 -443626.08512952      +1.09998010
        22 -443624.82622281      +1.25890671
        23 -443623.37710806      +1.44911475
        24 -443621.69659307      +1.68051499
        25 -443619.72773169      +1.96886137
        26 -443617.38867249      +2.33905921
        27 -443614.55640050      +2.83227199
        28 -443611.03214975      +3.52425075
        29 -443606.45593545      +4.57621430
        30 -443600.09497521      +6.36096024
        31 -443590.58653042      +9.50844479
        32 -443576.29517739     +14.29135303
        33 -443554.78026057     +21.51491682
        34 -443521.40103749     +33.37922308
        35 -443467.69067389     +53.71036360
        36 -443380.32959637     +87.36107752
        37 -443229.14798433    +151.18161203
        38 -442967.84286950    +261.30511484
        39 -442510.18973040    +457.65313910
        40 -441654.64477580    +855.54495459
        41 -439992.31601987   +1662.32875594
        42 -436586.11960183   +3406.19641803
        43 -431055.54884113   +5530.57076071
        44 -427233.27835778   +3822.27048334
        45 -426238.20868517    +995.06967261
        46 -425907.45295015    +330.75573502
        47 -425676.56741199    +230.88553815
        48 -425511.55459726    +165.01281473
        49 -425410.87163715    +100.68296012
        50 -425357.52802609     +53.34361106
        51 -425328.54508168     +28.98294441
        52 -425312.72147060     +15.82361108
        53 -425304.07652004      +8.64495056
        54 -425299.35015995      +4.72636009
        55 -425296.76263156      +2.58752839
        56 -425295.34313777      +1.41949379
        57 -425294.56250998      +0.78062779
        58 -425294.13207705      +0.43043293
        59 -425293.89407278      +0.23800426
        60 -425293.76207608      +0.13199670
        61 -425293.68863246      +0.07344362
        62 -425293.64762040      +0.04101205
        63 -425293.62462543      +0.02299498
        64 -425293.61167274      +0.01295269
        65 -425293.60433812      +0.00733461

2026-03-08 16:11:13 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:11:13 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.447935
2026-03-08 16:11:13 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.502448
2026-03-08 16:11:13 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.729060
2026-03-08 16:11:13 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 2

=== Training HMM with n_states=4 ===

         1 -655926.98581811             +nan
         2 -480581.69194049 +175345.29387762
         3 -424943.57038984  +55638.12155065
         4 -410636.71007179  +14306.86031805
         5 -408333.86751751   +2302.84255428
         6 -407622.70316428    +711.16435323
         7 -407275.86038724    +346.84277704
         8 -407060.43702354    +215.42336370
         9 -406912.68135716    +147.75566637
        10 -406813.98555782     +98.69579934
        11 -406746.54554575     +67.44001208
        12 -406699.14432120     +47.40122454
        13 -406662.64802591     +36.49629530
        14 -406633.27037746     +29.37764844
        15 -406608.78090566     +24.48947180
        16 -406585.97065519     +22.81025047
        17 -406562.90650274     +23.06415245
        18 -406537.14898331     +25.75751943
        19 -406500.94204910     +36.20693421
        20 -406475.11518411     +25.82686498
        21 -406451.71052718     +23.40465694
        22 -406428.60405792     +23.10646926
        23 -406406.29657761     +22.30748031
        24 -406383.10743877     +23.18913884
        25 -406358.58753655     +24.51990222
        26 -406330.73934285     +27.84819370
        27 -406293.75675012     +36.98259273
        28 -406258.27410938     +35.48264074
        29 -406220.86070253     +37.41340686
        30 -406179.54234897     +41.31835355
        31 -406134.08631113     +45.45603784
        32 -406077.57331760     +56.51299353
        33 -406008.94177647     +68.63154112
        34 -405923.74493941     +85.19683707
        35 -405817.62703896    +106.11790045
        36 -405686.32687897    +131.30015999
        37 -405518.61145024    +167.71542873
        38 -405315.73566758    +202.87578265
        39 -405081.23711917    +234.49854841
        40 -404813.33147280    +267.90564638
        41 -404511.72776882    +301.60370398
        42 -404190.40103460    +321.32673422
        43 -403855.21744260    +335.18359200
        44 -403482.25866898    +372.95877362
        45 -403085.69089567    +396.56777331
        46 -402610.05129242    +475.63960325
        47 -401933.95494908    +676.09634334
        48 -401007.76899282    +926.18595626
        49 -400235.47194841    +772.29704441
        50 -399815.34582223    +420.12612618
        51 -399531.50157699    +283.84424524
        52 -399330.04258716    +201.45898984
        53 -399163.91018211    +166.13240504
        54 -398999.78442236    +164.12575975
        55 -398851.42377334    +148.36064903
        56 -398738.06490011    +113.35887323
        57 -398643.01026101     +95.05463910
        58 -398560.73641043     +82.27385058
        59 -398480.51854095     +80.21786948
        60 -398407.76973486     +72.74880610
        61 -398344.36623241     +63.40350245
        62 -398291.52224634     +52.84398607
        63 -398250.48331925     +41.03892709
        64 -398211.36146285     +39.12185640
        65 -398166.01301063     +45.34845222
        66 -398129.26592972     +36.74708091
        67 -398104.16731487     +25.09861485
        68 -398082.49646508     +21.67084979
        69 -398064.27364253     +18.22282255
        70 -398050.30597171     +13.96767082
        71 -398040.09430029     +10.21167142
        72 -398032.73461642      +7.35968386
        73 -398027.37683528      +5.35778114
        74 -398023.36138681      +4.01544846
        75 -398020.23497214      +3.12641467
        76 -398017.70899345      +2.52597870
        77 -398015.61015801      +2.09883544
        78 -398013.84117115      +1.76898686
        79 -398012.35150324      +1.48966791
        80 -398011.11409725      +1.23740599
        81 -398010.10712234      +1.00697491
        82 -398009.30436761      +0.80275473
        83 -398008.67490012      +0.62946749
        84 -398008.18702118      +0.48787894
        85 -398007.81177523      +0.37524595
        86 -398007.52458557      +0.28718966
        87 -398007.30547709      +0.21910848
        88 -398007.13860192      +0.16687517
        89 -398007.01151997      +0.12708196
        90 -398006.91442996      +0.09709000
        91 -398006.83937706      +0.07505290
        92 -398006.77933027      +0.06004680
        93 -398006.72685844      +0.05247183
        94 -398006.67188132      +0.05497712
        95 -398006.59771385      +0.07416746
        96 -398006.47516293      +0.12255093
        97 -398006.25874060      +0.21642232
        98 -398005.90052581      +0.35821479
        99 -398005.39796502      +0.50256078
       100 -398004.83476584      +0.56319918
       101 -398004.33376144      +0.50100440
       102 -398003.96706993      +0.36669151
       103 -398003.73477395      +0.23229599
       104 -398003.60139918      +0.13337476
       105 -398003.52944833      +0.07195085
       106 -398003.49196300      +0.03748533
       107 -398003.47268228      +0.01928071
       108 -398003.46270131      +0.00998097

2026-03-08 16:11:29 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:11:29 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.440155
2026-03-08 16:11:29 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.721360
2026-03-08 16:11:29 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.586683
2026-03-08 16:11:29 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.486031
2026-03-08 16:11:29 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 1

=== Training HMM with n_states=5 ===

         1 -692473.48437642             +nan
         2 -473771.81261364 +218701.67176278
         3 -415752.28860966  +58019.52400398
         4 -396470.40608022  +19281.88252944
         5 -388025.42730295   +8444.97877727
         6 -385707.72363267   +2317.70367028
         7 -384439.08902556   +1268.63460711
         8 -383374.68136031   +1064.40766524
         9 -382294.79520592   +1079.88615439
        10 -380961.16961642   +1333.62558950
        11 -378930.76927343   +2030.40034299
        12 -376495.61544618   +2435.15382725
        13 -374743.59638647   +1752.01905972
        14 -373706.56916747   +1037.02721900
        15 -373102.35762080    +604.21154667
        16 -372665.97944314    +436.37817766
        17 -372316.19634800    +349.78309514
        18 -372094.57091636    +221.62543164
        19 -371939.42751531    +155.14340105
        20 -371826.68319065    +112.74432466
        21 -371740.13061644     +86.55257421
        22 -371674.32435517     +65.80626127
        23 -371627.49034005     +46.83401512
        24 -371588.87301839     +38.61732166
        25 -371550.44113918     +38.43187921
        26 -371503.10434716     +47.33679202
        27 -371439.63541975     +63.46892741
        28 -371361.69625971     +77.93916005
        29 -371257.88246357    +103.81379614
        30 -371105.11168644    +152.77077713
        31 -370905.59508000    +199.51660644
        32 -370687.95214491    +217.64293508
        33 -370414.61273053    +273.33941438
        34 -370103.33636760    +311.27636293
        35 -369826.34816132    +276.98820628
        36 -369559.99735899    +266.35080233
        37 -369218.96252498    +341.03483401
        38 -368846.10386499    +372.85865999
        39 -368590.51670298    +255.58716201
        40 -368439.34823354    +151.16846944
        41 -368347.02187567     +92.32635788
        42 -368277.12661295     +69.89526272
        43 -368215.89255825     +61.23405470
        44 -368164.93727783     +50.95528042
        45 -368124.44681227     +40.49046557
        46 -368074.93200911     +49.51480316
        47 -368003.30307356     +71.62893555
        48 -367820.34488156    +182.95819200
        49 -367328.73271044    +491.61217112
        50 -366676.05085858    +652.68185185
        51 -366264.21812014    +411.83273845
        52 -365964.47724278    +299.74087736
        53 -365674.00511477    +290.47212801
        54 -365272.33391164    +401.67120313
        55 -364926.84823851    +345.48567313
        56 -364715.90423530    +210.94400322
        57 -364548.85333593    +167.05089937
        58 -364348.72794809    +200.12538783
        59 -364106.83610513    +241.89184296
        60 -363820.22586506    +286.61024007
        61 -363501.72679315    +318.49907191
        62 -363199.31506296    +302.41173019
        63 -362867.18249358    +332.13256939
        64 -362683.88241424    +183.30007933
        65 -362581.03949717    +102.84291707
        66 -362527.79065911     +53.24883806
        67 -362496.99335905     +30.79730006
        68 -362478.20155081     +18.79180824
        69 -362466.62183998     +11.57971084
        70 -362459.51525758      +7.10658240
        71 -362455.00890126      +4.50635632
        72 -362451.83632659      +3.17257468
        73 -362449.25408808      +2.58223851
        74 -362447.02488048      +2.22920759
        75 -362445.25932883      +1.76555165
        76 -362444.01188675      +1.24744208
        77 -362443.17853673      +0.83335002
        78 -362442.62856433      +0.54997240
        79 -362442.26422461      +0.36433972
        80 -362442.02108662      +0.24313799
        81 -362441.85768540      +0.16340122
        82 -362441.74721780      +0.11046760
        83 -362441.67217288      +0.07504492
        84 -362441.62098991      +0.05118297
        85 -362441.58596842      +0.03502148
        86 -362441.56194176      +0.02402667
        87 -362441.54542258      +0.01651918
        88 -362441.53404539      +0.01137719
        89 -362441.52619900      +0.00784639

2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.488806
2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.449153
2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.443192
2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.726774
2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.621313
2026-03-08 16:11:45 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 3

=== Training HMM with n_states=6 ===

         1 -796125.49226846             +nan
         2 -555913.82032651 +240211.67194195
         3 -461684.51935175  +94229.30097476
         4 -443008.13835846  +18676.38099329
         5 -432659.21043265  +10348.92792581
         6 -419166.04208212  +13493.16835054
         7 -404764.25070436  +14401.79137776
         8 -394087.85701391  +10676.39369045
         9 -388291.95813001   +5795.89888390
        10 -385897.37265581   +2394.58547420
        11 -384656.30860074   +1241.06405507
        12 -383415.46030544   +1240.84829530
        13 -382631.07462648    +784.38567896
        14 -382149.27927935    +481.79534713
        15 -381755.96061751    +393.31866184
        16 -381377.74054651    +378.22007100
        17 -380955.78373152    +421.95681499
        18 -380470.00226541    +485.78146612
        19 -379861.02232694    +608.97993847
        20 -379160.17178827    +700.85053867
        21 -378312.76203913    +847.40974915
        22 -377498.57446128    +814.18757785
        23 -376868.02350096    +630.55096032
        24 -376410.33241308    +457.69108788
        25 -376108.30683508    +302.02557800
        26 -375895.38251496    +212.92432012
        27 -375749.93352285    +145.44899211
        28 -375645.76114845    +104.17237440
        29 -375557.49483991     +88.26630854
        30 -375483.11681148     +74.37802843
        31 -375435.16994268     +47.94686881
        32 -375406.39389295     +28.77604973
        33 -375387.80519849     +18.58869446
        34 -375374.14164150     +13.66355698
        35 -375363.68042391     +10.46121760
        36 -375355.63510795      +8.04531596
        37 -375349.38921199      +6.24589596
        38 -375344.43570569      +4.95350629
        39 -375340.39445261      +4.04125308
        40 -375336.99536841      +3.39908420
        41 -375334.04889958      +2.94646883
        42 -375331.42075535      +2.62814423
        43 -375329.01416038      +2.40659497
        44 -375326.74309634      +2.27106405
        45 -375323.97360723      +2.76948911
        46 -375311.22802987     +12.74557735
        47 -375278.80110809     +32.42692178
        48 -375256.64713861     +22.15396948
        49 -375247.39757664      +9.24956197
        50 -375242.78551069      +4.61206595
        51 -375239.47945789      +3.30605280
        52 -375236.60341397      +2.87604392
        53 -375233.92366841      +2.67974556
        54 -375231.35940777      +2.56426064
        55 -375228.87010292      +2.48930485
        56 -375226.42818610      +2.44191682
        57 -375224.01136944      +2.41681666
        58 -375221.59999236      +2.41137707
        59 -375219.17583555      +2.42415681
        60 -375216.72136416      +2.45447139
        61 -375214.21897947      +2.50238468
        62 -375211.64996185      +2.56901762
        63 -375208.99265005      +2.65731180
        64 -375206.21912382      +2.77352623
        65 -375203.29011904      +2.92900478
        66 -375200.15384506      +3.13627398
        67 -375196.77088766      +3.38295740
        68 -375193.16325355      +3.60763411
        69 -375189.38938176      +3.77387179
        70 -375185.46990311      +3.91947865
        71 -375181.38614734      +4.08375577
        72 -375177.10162887      +4.28451847
        73 -375172.56565971      +4.53596916
        74 -375167.69419201      +4.87146770
        75 -375162.27108452      +5.42310749
        76 -375155.42983773      +6.84124679
        77 -375145.33670452     +10.09313321
        78 -375134.07492482     +11.26177970
        79 -375121.01662903     +13.05829579
        80 -375096.52688902     +24.48974002
        81 -375042.43071141     +54.09617761
        82 -374922.14172277    +120.28898864
        83 -374732.83690798    +189.30481479
        84 -374615.48117750    +117.35573049
        85 -374514.60947063    +100.87170686
        86 -374381.18447405    +133.42499658
        87 -374240.77411911    +140.41035495
        88 -374092.87629471    +147.89782439
        89 -373893.45091297    +199.42538174
        90 -373666.04654014    +227.40437283
        91 -373459.42833686    +206.61820328
        92 -373247.83489121    +211.59344565
        93 -373068.57594288    +179.25894833
        94 -372885.58505837    +182.99088451
        95 -372676.79623190    +208.78882647
        96 -372452.86926196    +223.92696994
        97 -372153.37917030    +299.49009165
        98 -371648.07321510    +505.30595520
        99 -370916.96833180    +731.10488330
       100 -370064.20094974    +852.76738207
       101 -369203.61886757    +860.58208216
       102 -368308.59881512    +895.02005245
       103 -367348.54978603    +960.04902910
       104 -366242.94496344   +1105.60482258
       105 -365182.61688109   +1060.32808235
       106 -364076.64992585   +1105.96695524
       107 -360387.40922289   +3689.24070296
       108 -356083.81210285   +4303.59712004
       109 -354624.79730433   +1459.01479852
       110 -354052.61299259    +572.18431174
       111 -353798.25251233    +254.36048025
       112 -353648.09543136    +150.15708098
       113 -353555.86273263     +92.23269873
       114 -353504.99837970     +50.86435292
       115 -353469.48359311     +35.51478659
       116 -353438.97528078     +30.50831233
       117 -353421.39568423     +17.57959655
       118 -353411.60018697      +9.79549726
       119 -353404.14325070      +7.45693627
       120 -353398.47210637      +5.67114433
       121 -353394.71467673      +3.75742964
       122 -353392.34478435      +2.36989239
       123 -353390.80553212      +1.53925223
       124 -353389.75946018      +1.04607194
       125 -353389.02209465      +0.73736553
       126 -353388.48887524      +0.53321941
       127 -353388.09668436      +0.39219088
       128 -353387.80507952      +0.29160485
       129 -353387.58681779      +0.21826172
       130 -353387.42281789      +0.16399990
       131 -353387.29933120      +0.12348669
       132 -353387.20625901      +0.09307219
       133 -353387.13609114      +0.07016788
       134 -353387.08319959      +0.05289155
       135 -353387.04334779      +0.03985180
       136 -353387.01333848      +0.03000931
       137 -353386.99075569      +0.02258279
       138 -353386.97377309      +0.01698261
       139 -353386.96101023      +0.01276286
       140 -353386.95142429      +0.00958593

2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.386638
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.607015
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.756480
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.474779
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.514607
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.620395
2026-03-08 16:12:09 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 2

=== Training HMM with n_states=7 ===

         1 -671985.47089706             +nan
         2 -473608.81752466 +198376.65337240
         3 -425154.77838589  +48454.03913877
         4 -403796.63341529  +21358.14497060
         5 -393477.67348529  +10318.95993000
         6 -387792.75540876   +5684.91807654
         7 -383422.98375686   +4369.77165190
         8 -379046.98724767   +4375.99650918
         9 -374706.99102749   +4339.99622018
        10 -371009.31479943   +3697.67622807
        11 -367375.54913712   +3633.76566230
        12 -363460.80064100   +3914.74849612
        13 -359299.85113126   +4160.94950975
        14 -354969.63610358   +4330.21502767
        15 -351210.58209628   +3759.05400730
        16 -347795.46831568   +3415.11378060
        17 -344709.07069994   +3086.39761574
        18 -342098.92486855   +2610.14583139
        19 -340197.61784216   +1901.30702639
        20 -339014.05083387   +1183.56700829
        21 -338195.35349192    +818.69734194
        22 -337604.78355586    +590.56993607
        23 -337109.78966950    +494.99388636
        24 -336721.01215588    +388.77751362
        25 -336446.91145588    +274.10070000
        26 -336234.77628101    +212.13517487
        27 -336032.68198242    +202.09429859
        28 -335831.97383369    +200.70814873
        29 -335626.51865311    +205.45518058
        30 -335414.03082047    +212.48783264
        31 -335219.51725336    +194.51356711
        32 -335055.20547935    +164.31177401
        33 -334919.22330340    +135.98217595
        34 -334805.94560223    +113.27770117
        35 -334700.91408754    +105.03151469
        36 -334593.43184594    +107.48224160
        37 -334479.28800105    +114.14384488
        38 -334367.07845474    +112.20954632
        39 -334265.52314074    +101.55531400
        40 -334173.33260235     +92.19053839
        41 -334091.10064459     +82.23195776
        42 -334012.69877423     +78.40187036
        43 -333931.48361987     +81.21515436
        44 -333847.89138125     +83.59223861
        45 -333762.47876381     +85.41261744
        46 -333659.59766428    +102.88109953
        47 -333544.32137409    +115.27629020
        48 -333440.34759740    +103.97377668
        49 -333346.56405018     +93.78354722
        50 -333261.74989654     +84.81415363
        51 -333183.74371431     +78.00618224
        52 -333108.60951637     +75.13419793
        53 -333034.52005789     +74.08945849
        54 -332961.85766824     +72.66238964
        55 -332889.14390718     +72.71376106
        56 -332801.30901517     +87.83489201
        57 -332680.02290046    +121.28611471
        58 -332578.21560570    +101.80729476
        59 -332517.82910726     +60.38649844
        60 -332480.64113026     +37.18797700
        61 -332455.60709440     +25.03403585
        62 -332437.85912498     +17.74796943
        63 -332424.89310413     +12.96602085
        64 -332415.21483915      +9.67826498
        65 -332407.76513067      +7.44970848
        66 -332401.57804823      +6.18708243
        67 -332396.06816429      +5.50988394
        68 -332391.88760668      +4.18055762
        69 -332388.99353011      +2.89407656
        70 -332386.87837086      +2.11515925
        71 -332385.25975819      +1.61861268
        72 -332383.97622168      +1.28353651
        73 -332382.92460806      +1.05161362
        74 -332382.03985553      +0.88475254
        75 -332381.28518785      +0.75466768
        76 -332380.64316501      +0.64202284
        77 -332380.10611886      +0.53704615
        78 -332379.66806324      +0.43805563
        79 -332379.32028595      +0.34777728
        80 -332379.05075386      +0.26953210
        81 -332378.84570607      +0.20504778
        82 -332378.69161810      +0.15408798
        83 -332378.57644706      +0.11517104
        84 -332378.48900972      +0.08743733
        85 -332378.40670360      +0.08230612
        86 -332378.18056206      +0.22614154
        87 -332377.03314158      +1.14742048
        88 -332374.56338512      +2.46975645
        89 -332364.24684372     +10.31654141
        90 -332255.85389750    +108.39294622
        91 -331945.07174458    +310.78215292
        92 -331516.82123474    +428.25050984
        93 -331050.19509202    +466.62614272
        94 -330536.77406893    +513.42102309
        95 -330007.62787020    +529.14619873
        96 -329446.01766009    +561.61021011
        97 -328912.32426896    +533.69339113
        98 -328379.68981495    +532.63445401
        99 -327927.47713914    +452.21267581
       100 -327593.89451525    +333.58262389
       101 -327291.27196411    +302.62255114
       102 -326867.08569991    +424.18626420
       103 -326451.99011724    +415.09558267
       104 -326135.49697499    +316.49314225
       105 -325929.06045856    +206.43651643
       106 -325771.37355639    +157.68690217
       107 -325661.45320909    +109.92034729
       108 -325589.82281314     +71.63039596
       109 -325541.26607354     +48.55673960
       110 -325501.67007889     +39.59599465
       111 -325462.09433098     +39.57574791
       112 -325421.11554567     +40.97878531
       113 -325371.64833759     +49.46720808
       114 -325295.95618741     +75.69215018
       115 -325250.00520804     +45.95097938
       116 -325217.07477512     +32.93043292
       117 -325192.52060867     +24.55416645
       118 -325173.94382158     +18.57678709
       119 -325159.22225191     +14.72156967
       120 -325146.75081566     +12.47143625
       121 -325135.73874882     +11.01206684
       122 -325126.00382735      +9.73492147
       123 -325117.63055894      +8.37326840
       124 -325110.67842331      +6.95213563
       125 -325105.09232675      +5.58609657
       126 -325100.75729300      +4.33503374
       127 -325097.51611330      +3.24117970
       128 -325095.16679309      +2.34932022
       129 -325093.49278069      +1.67401239
       130 -325092.30633524      +1.18644545
       131 -325091.46454724      +0.84178800
       132 -325090.86496875      +0.59957849
       133 -325090.43576579      +0.42920296
       134 -325090.12684058      +0.30892521
       135 -325089.90321700      +0.22362358
       136 -325089.74039431      +0.16282268
       137 -325089.62113768      +0.11925663
       138 -325089.53326753      +0.08787015
       139 -325089.46813484      +0.06513269
       140 -325089.41956657      +0.04856827
       141 -325089.38313388      +0.03643269
       142 -325089.35564244      +0.02749143
       143 -325089.33477601      +0.02086643
       144 -325089.31884598      +0.01593003
       145 -325089.30661475      +0.01223124
       146 -325089.29717037      +0.00944438

2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.608618
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.561728
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.764300
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.381682
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.537485
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.499121
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=6 -> mean_max_reach_y=0.486114
2026-03-08 16:12:37 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 2

=== Training HMM with n_states=8 ===

         1 -754092.48366630             +nan
         2 -507245.60985889 +246846.87380742
         3 -416329.47856236  +90916.13129653
         4 -383883.21212720  +32446.26643516
         5 -372530.25466232  +11352.95746488
         6 -364907.66588087   +7622.58878145
         7 -359980.25090708   +4927.41497380
         8 -357187.33479175   +2792.91611532
         9 -355482.68111636   +1704.65367539
        10 -354238.90042280   +1243.78069355
        11 -353176.24466332   +1062.65575948
        12 -351889.07858429   +1287.16607903
        13 -350130.35288233   +1758.72570196
        14 -347495.12194633   +2635.23093600
        15 -343697.22744039   +3797.89450594
        16 -339517.42132909   +4179.80611131
        17 -334648.99873253   +4868.42259656
        18 -329928.23336513   +4720.76536740
        19 -327627.65668893   +2300.57667619
        20 -325556.44673676   +2071.20995217
        21 -324543.20980083   +1013.23693593
        22 -323951.50059395    +591.70920689
        23 -323497.22381408    +454.27677986
        24 -323121.45573184    +375.76808224
        25 -322795.38675656    +326.06897529
        26 -322514.19178711    +281.19496944
        27 -322261.46670209    +252.72508503
        28 -322042.50455705    +218.96214504
        29 -321837.32854860    +205.17600845
        30 -321666.93914216    +170.38940644
        31 -321541.22882645    +125.71031571
        32 -321432.05773821    +109.17108824
        33 -321328.26138576    +103.79635245
        34 -321231.54141134     +96.71997442
        35 -321153.33780394     +78.20360739
        36 -321097.44192420     +55.89587975
        37 -321048.36733137     +49.07459283
        38 -321000.72025879     +47.64707258
        39 -320953.67159438     +47.04866441
        40 -320904.15465090     +49.51694349
        41 -320845.80910267     +58.34554822
        42 -320771.01365700     +74.79544567
        43 -320669.16312264    +101.85053436
        44 -320525.32094585    +143.84217679
        45 -320308.58238443    +216.73856142
        46 -319884.87159841    +423.71078602
        47 -318830.32858028   +1054.54301813
        48 -317160.35177433   +1669.97680595
        49 -315638.01831128   +1522.33346305
        50 -314682.96279156    +955.05551972
        51 -314142.09998239    +540.86280917
        52 -313717.82550238    +424.27448001
        53 -313334.10991988    +383.71558250
        54 -312931.84267514    +402.26724474
        55 -312575.49943207    +356.34324307
        56 -312198.69375825    +376.80567383
        57 -311797.37954930    +401.31420895
        58 -311257.43352983    +539.94601947
        59 -310603.55142393    +653.88210590
        60 -309991.96101618    +611.59040775
        61 -309448.04949453    +543.91152165
        62 -308975.78369346    +472.26580107
        63 -308458.97388224    +516.80981122
        64 -307930.74328330    +528.23059894
        65 -307523.28994683    +407.45333647
        66 -307189.61804913    +333.67189770
        67 -306927.36666519    +262.25138394
        68 -306712.64809847    +214.71856672
        69 -306572.60226692    +140.04583155
        70 -306497.70983106     +74.89243586
        71 -306457.09047738     +40.61935367
        72 -306431.87078475     +25.21969263
        73 -306413.53710135     +18.33368340
        74 -306397.67683800     +15.86026335
        75 -306382.66636490     +15.01047310
        76 -306365.08775945     +17.57860545
        77 -306336.74591641     +28.34184304
        78 -306295.17434999     +41.57156643
        79 -306254.43858860     +40.73576139
        80 -306223.47660364     +30.96198497
        81 -306199.90414027     +23.57246337
        82 -306180.03993619     +19.86420408
        83 -306161.58034530     +18.45959089
        84 -306142.56635417     +19.01399113
        85 -306121.90155133     +20.66480284
        86 -306100.92343027     +20.97812106
        87 -306081.20320192     +19.72022836
        88 -306062.62752538     +18.57567653
        89 -306046.31735455     +16.31017084
        90 -306031.00676123     +15.31059332
        91 -306014.82210030     +16.18466093
        92 -305998.11823770     +16.70386260
        93 -305978.37829704     +19.73994066
        94 -305956.53911195     +21.83918509
        95 -305932.25926823     +24.27984372
        96 -305899.63017846     +32.62908977
        97 -305867.56788280     +32.06229567
        98 -305842.06231307     +25.50556973
        99 -305824.84388544     +17.21842763
       100 -305812.94915293     +11.89473251
       101 -305804.37841830      +8.57073462
       102 -305797.97220134      +6.40621696
       103 -305793.02216808      +4.95003326
       104 -305789.11324936      +3.90891872
       105 -305785.53855710      +3.57469226
       106 -305781.65228630      +3.88627080
       107 -305777.26993391      +4.38235239
       108 -305772.43170697      +4.83822694
       109 -305767.10979580      +5.32191117
       110 -305760.93259161      +6.17720419
       111 -305753.16097443      +7.77161718
       112 -305742.72344248     +10.43753195
       113 -305727.44432780     +15.27911468
       114 -305707.18145953     +20.26286827
       115 -305686.16719012     +21.01426941
       116 -305665.68848242     +20.47870770
       117 -305645.70750296     +19.98097946
       118 -305628.60097761     +17.10652535
       119 -305616.42033669     +12.18064092
       120 -305607.54678681      +8.87354987
       121 -305600.59896946      +6.94781735
       122 -305595.30715175      +5.29181772
       123 -305591.42666935      +3.88048240
       124 -305588.73287960      +2.69378975
       125 -305586.93095149      +1.80192811
       126 -305585.70290503      +1.22804647
       127 -305584.80112444      +0.90178059
       128 -305584.04938662      +0.75173782
       129 -305583.35008958      +0.69929704
       130 -305582.75094892      +0.59914066
       131 -305582.34733679      +0.40361213
       132 -305582.10445041      +0.24288638
       133 -305581.95106677      +0.15338365
       134 -305581.84657884      +0.10448793
       135 -305581.77123418      +0.07534466
       136 -305581.71476660      +0.05646758
       137 -305581.67124587      +0.04352073
       138 -305581.63686842      +0.03437745
       139 -305581.60897936      +0.02788905
       140 -305581.58561904      +0.02336032
       141 -305581.56529591      +0.02032313
       142 -305581.54686296      +0.01843296
       143 -305581.52945261      +0.01741035
       144 -305581.51245643      +0.01699618
       145 -305581.49554232      +0.01691412
       146 -305581.47869163      +0.01685069
       147 -305581.46221731      +0.01647431
       148 -305581.44670821      +0.01550910
       149 -305581.43286647      +0.01384174
       150 -305581.42127627      +0.01159020
       151 -305581.41221307      +0.00906320

2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.435867
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.759202
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.609267
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.484325
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.411386
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.584201
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=6 -> mean_max_reach_y=0.569651
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=7 -> mean_max_reach_y=0.524598
2026-03-08 16:13:10 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 1

=== Training HMM with n_states=9 ===

         1 -734166.72714569             +nan
         2 -450190.57049606 +283976.15664963
         3 -406016.08509200  +44174.48540405
         4 -395573.86437519  +10442.22071681
         5 -389517.45190984   +6056.41246535
         6 -386281.21837525   +3236.23353460
         7 -384662.78441372   +1618.43396153
         8 -383535.04787412   +1127.73653960
         9 -382543.83750552    +991.21036859
        10 -381533.37611835   +1010.46138718
        11 -379813.40608644   +1719.97003191
        12 -374291.17302924   +5522.23305720
        13 -368313.37512556   +5977.79790368
        14 -365766.19498733   +2547.18013823
        15 -363936.14557585   +1830.04941149
        16 -362133.35867832   +1802.78689752
        17 -360136.77804228   +1996.58063604
        18 -357666.23765278   +2470.54038950
        19 -354448.10947436   +3218.12817842
        20 -350116.44744448   +4331.66202987
        21 -345071.96278504   +5044.48465944
        22 -341455.15242983   +3616.81035521
        23 -339407.05428278   +2048.09814705
        24 -337981.13073550   +1425.92354728
        25 -336984.28495979    +996.84577571
        26 -336092.84334977    +891.44161002
        27 -334539.68459307   +1553.15875669
        28 -332135.79448602   +2403.89010705
        29 -329794.91734252   +2340.87714351
        30 -329212.39087402    +582.52646850
        31 -329023.53213119    +188.85874283
        32 -328928.94665671     +94.58547448
        33 -328844.90884406     +84.03781265
        34 -328759.31066269     +85.59818137
        35 -328681.34689664     +77.96376605
        36 -328609.38137010     +71.96552654
        37 -328540.54356935     +68.83780075
        38 -328474.10613760     +66.43743175
        39 -328418.35854736     +55.74759023
        40 -328370.03585898     +48.32268839
        41 -328319.78057673     +50.25528224
        42 -328265.27594645     +54.50463028
        43 -328220.60887913     +44.66706732
        44 -328193.10530072     +27.50357842
        45 -328176.23030656     +16.87499416
        46 -328161.31935835     +14.91094821
        47 -328139.74340447     +21.57595388
        48 -328109.13845926     +30.60494520
        49 -328075.61754999     +33.52090927
        50 -328043.52859612     +32.08895388
        51 -328012.80012646     +30.72846966
        52 -327982.12297119     +30.67715526
        53 -327950.71534381     +31.40762738
        54 -327917.73662682     +32.97871699
        55 -327881.91815315     +35.81847368
        56 -327841.47412972     +40.44402343
        57 -327794.41629281     +47.05783691
        58 -327738.81405290     +55.60223991
        59 -327673.00276628     +65.81128662
        60 -327595.59128740     +77.41147888
        61 -327497.00378354     +98.58750386
        62 -327377.65607717    +119.34770637
        63 -327242.93444146    +134.72163571
        64 -327086.78426664    +156.15017482
        65 -326901.15416614    +185.63010050
        66 -326681.76520980    +219.38895634
        67 -326394.27513275    +287.49007705
        68 -325982.51679840    +411.75833435
        69 -325490.64601648    +491.87078192
        70 -325018.70873746    +471.93727902
        71 -324562.77280824    +455.93592923
        72 -324075.97044846    +486.80235978
        73 -323640.40375692    +435.56669154
        74 -323264.53588465    +375.86787227
        75 -322947.56712533    +316.96875932
        76 -322679.99103418    +267.57609114
        77 -322451.28066435    +228.71036983
        78 -322270.05279489    +181.22786946
        79 -322092.90029849    +177.15249639
        80 -321907.69402824    +185.20627025
        81 -321728.03223426    +179.66179398
        82 -321576.19123674    +151.84099752
        83 -321438.48079642    +137.71044032
        84 -321328.61814175    +109.86265466
        85 -321236.17986762     +92.43827413
        86 -321146.37240245     +89.80746518
        87 -321038.27196126    +108.10044119
        88 -320912.43876333    +125.83319793
        89 -320804.02270247    +108.41606086
        90 -320692.49306364    +111.52963883
        91 -320508.18084295    +184.31222069
        92 -320024.95198227    +483.22886068
        93 -319602.50045345    +422.45152882
        94 -319339.88874395    +262.61170950
        95 -319064.00513371    +275.88361024
        96 -318734.08218609    +329.92294763
        97 -318329.28050999    +404.80167609
        98 -317819.45509448    +509.82541552
        99 -317122.20066114    +697.25443333
       100 -316008.62229346   +1113.57836768
       101 -314189.22754645   +1819.39474701
       102 -311835.79200133   +2353.43554512
       103 -309435.57086700   +2400.22113433
       104 -307185.88184307   +2249.68902393
       105 -305169.00845026   +2016.87339281
       106 -303511.43895757   +1657.56949269
       107 -302389.82763186   +1121.61132570
       108 -301903.66697658    +486.16065529
       109 -301583.99596704    +319.67100954
       110 -301365.15713737    +218.83882967
       111 -301219.71258028    +145.44455708
       112 -301118.63143849    +101.08114179
       113 -301037.21521369     +81.41622480
       114 -300957.28692892     +79.92828478
       115 -300880.54206992     +76.74485900
       116 -300799.88911387     +80.65295605
       117 -300711.40533701     +88.48377686
       118 -300616.98077182     +94.42456519
       119 -300518.29953346     +98.68123836
       120 -300409.17567445    +109.12385901
       121 -300277.17400725    +132.00166720
       122 -300125.88894232    +151.28506494
       123 -299944.90486327    +180.98407904
       124 -299794.47264777    +150.43221550
       125 -299690.28995817    +104.18268960
       126 -299612.52287461     +77.76708356
       127 -299550.14249371     +62.38038090
       128 -299497.94719033     +52.19530338
       129 -299453.47035014     +44.47684019
       130 -299414.04113104     +39.42921910
       131 -299375.51745987     +38.52367116
       132 -299338.12917598     +37.38828390
       133 -299301.24841951     +36.88075646
       134 -299259.11150012     +42.13691939
       135 -299201.46635605     +57.64514408
       136 -299131.84587268     +69.62048337
       137 -299054.50587868     +77.33999399
       138 -298982.99397662     +71.51190206
       139 -298925.92135002     +57.07262660
       140 -298876.13574344     +49.78560658
       141 -298828.47153029     +47.66421315
       142 -298789.96973722     +38.50179307
       143 -298763.48932422     +26.48041301
       144 -298744.35581240     +19.13351182
       145 -298728.21566844     +16.14014395
       146 -298712.50488723     +15.71078121
       147 -298698.54532668     +13.95956055
       148 -298687.45609413     +11.08923255
       149 -298678.29375969      +9.16233444
       150 -298670.19308955      +8.10067014
       151 -298661.21149261      +8.98159694
       152 -298640.67751282     +20.53397979
       153 -298596.75750793     +43.92000488
       154 -298557.81727791     +38.94023002
       155 -298537.15264512     +20.66463279
       156 -298526.66569835     +10.48694677
       157 -298519.66275251      +7.00294585
       158 -298513.91140770      +5.75134480
       159 -298508.75938878      +5.15201893
       160 -298503.98411096      +4.77527782
       161 -298499.48462540      +4.49948556
       162 -298495.20306059      +4.28156482
       163 -298491.10171618      +4.10134441
       164 -298487.15397854      +3.94773764
       165 -298483.33950945      +3.81446909
       166 -298479.64096714      +3.69854230
       167 -298475.88393064      +3.75703651
       168 -298468.31786336      +7.56606728
       169 -298463.13909529      +5.17876807
       170 -298459.47882515      +3.66027015
       171 -298456.01624424      +3.46258091
       172 -298452.62760288      +3.38864136
       173 -298449.26840267      +3.35920021
       174 -298445.90204208      +3.36636059
       175 -298442.47432675      +3.42771533
       176 -298438.86071504      +3.61361171
       177 -298434.76447938      +4.09623566
       178 -298430.11749154      +4.64698784
       179 -298425.63857339      +4.47891816
       180 -298421.34649890      +4.29207449
       181 -298417.06937518      +4.27712372
       182 -298412.74888563      +4.32048955
       183 -298408.35732665      +4.39155898
       184 -298403.87296235      +4.48436430
       185 -298399.27455680      +4.59840555
       186 -298394.54020950      +4.73434731
       187 -298389.64718707      +4.89302243
       188 -298384.56836900      +5.07881807
       189 -298378.64911701      +5.91925199
       190 -298349.36589953     +29.28321748
       191 -298273.10966928     +76.25623025
       192 -298226.60346730     +46.50620198
       193 -298205.16463545     +21.43883185
       194 -298188.67293898     +16.49169647
       195 -298172.82681365     +15.84612532
       196 -298156.54445399     +16.28235966
       197 -298138.87684256     +17.66761143
       198 -298119.34298898     +19.53385358
       199 -298100.42103081     +18.92195817
       200 -298081.68849658     +18.73253423
       201 -298062.18904147     +19.49945512
       202 -298041.25938747     +20.92965400
       203 -298018.02382571     +23.23556176
       204 -297991.70665194     +26.31717377
       205 -297963.20592923     +28.50072271
       206 -297933.06274935     +30.14317988
       207 -297900.59508612     +32.46766322
       208 -297865.37908477     +35.21600136
       209 -297827.04270120     +38.33638356
       210 -297784.61436291     +42.42833829
       211 -297735.48431641     +49.13004651
       212 -297674.93432512     +60.54999129
       213 -297606.01633521     +68.91798992
       214 -297530.43967775     +75.57665746
       215 -297451.00219656     +79.43748119
       216 -297367.51179014     +83.49040642
       217 -297279.94063618     +87.57115396
       218 -297176.88008447    +103.06055171
       219 -297048.70817377    +128.17191070
       220 -296902.35207266    +146.35610111
       221 -296703.15853999    +199.19353267
       222 -296468.55592438    +234.60261560
       223 -296274.11312740    +194.44279699
       224 -296111.31005701    +162.80307039
       225 -295986.47534998    +124.83470703
       226 -295890.88810366     +95.58724632
       227 -295818.12237450     +72.76572916
       228 -295763.56407384     +54.55830067
       229 -295722.36761135     +41.19646249
       230 -295691.19115020     +31.17646115
       231 -295666.98239073     +24.20875947
       232 -295646.53213162     +20.45025911
       233 -295616.28199730     +30.25013432
       234 -295555.50549604     +60.77650126
       235 -295501.28948014     +54.21601589
       236 -295442.29853799     +58.99094215
       237 -295384.40815739     +57.89038060
       238 -295352.63909408     +31.76906331
       239 -295331.71796654     +20.92112754
       240 -295313.45234905     +18.26561749
       241 -295294.65949751     +18.79285153
       242 -295275.99751539     +18.66198213
       243 -295257.14757815     +18.84993724
       244 -295234.26505729     +22.88252086
       245 -295207.98591542     +26.27914187
       246 -295180.61715295     +27.36876247
       247 -295152.44753471     +28.16961824
       248 -295126.38536320     +26.06217150
       249 -295100.90316632     +25.48219688
       250 -295075.51728166     +25.38588466
       251 -295050.61036759     +24.90691407
       252 -295027.02370764     +23.58665995
       253 -295005.58493945     +21.43876819
       254 -294986.83437080     +18.75056865
       255 -294971.01637420     +15.81799660
       256 -294958.10599069     +12.91038351
       257 -294947.86079799     +10.24519270
       258 -294939.89323175      +7.96756623
       259 -294933.67651354      +6.21671821
       260 -294928.25151075      +5.42500279
       261 -294921.85416916      +6.39734159
       262 -294913.60969395      +8.24447521
       263 -294905.30508327      +8.30461068
       264 -294898.67774044      +6.62734284
       265 -294893.57915964      +5.09858080
       266 -294889.34076707      +4.23839257
       267 -294885.50835258      +3.83241449
       268 -294881.82008486      +3.68826772
       269 -294878.09618162      +3.72390324
       270 -294874.18220055      +3.91398107
       271 -294869.92345099      +4.25874956
       272 -294865.14092777      +4.78252323
       273 -294859.58815275      +5.55277502
       274 -294852.87213785      +6.71601489
       275 -294844.28792467      +8.58421318
       276 -294832.30889043     +11.97903424
       277 -294813.29472611     +19.01416431
       278 -294779.95541118     +33.33931494
       279 -294735.13581778     +44.81959340
       280 -294688.72803446     +46.40778332
       281 -294639.61798866     +49.11004580
       282 -294588.96185149     +50.65613717
       283 -294543.77036527     +45.19148621
       284 -294506.76404274     +37.00632253
       285 -294475.12187226     +31.64217048
       286 -294446.53297300     +28.58889926
       287 -294419.16187351     +27.37109949
       288 -294395.27295135     +23.88892216
       289 -294378.16437222     +17.10857914
       290 -294366.15744363     +12.00692859
       291 -294356.16784224      +9.98960139
       292 -294341.05933004     +15.10851220
       293 -294323.83404995     +17.22528009
       294 -294313.34462216     +10.48942779
       295 -294307.68407074      +5.66055142
       296 -294304.40440512      +3.27966562
       297 -294302.31919542      +2.08520970
       298 -294300.85935302      +1.45984240
       299 -294299.68578627      +1.17356675
       300 -294298.54011356      +1.14567270
       301 -294297.29162458      +1.24848899
       302 -294296.14384776      +1.14777682
       303 -294295.29325656      +0.85059120
       304 -294294.53720531      +0.75605125
       305 -294292.91841773      +1.61878758
       306 -294286.23680975      +6.68160798
       307 -294264.29783631     +21.93897344
       308 -294223.30130143     +40.99653488
       309 -294172.19929951     +51.10200192
       310 -294136.73405075     +35.46524876
       311 -294117.85473262     +18.87931813
       312 -294107.47564976     +10.37908286
       313 -294100.88114656      +6.59450320
       314 -294096.20188691      +4.67925966
       315 -294092.69600377      +3.50588314
       316 -294089.96894840      +2.72705536
       317 -294087.73732905      +2.23161935
       318 -294085.64908762      +2.08824143
       319 -294080.98147851      +4.66760912
       320 -294064.60780902     +16.37366949
       321 -294059.56249748      +5.04531153
       322 -294056.62868430      +2.93381319
       323 -294054.07902828      +2.54965602
       324 -294051.65216663      +2.42686165
       325 -294049.19498295      +2.45718368
       326 -294046.53807441      +2.65690854
       327 -294043.42661916      +3.11145525
       328 -294039.42167243      +4.00494673
       329 -294033.86213762      +5.55953482
       330 -294026.24771089      +7.61442673
       331 -294016.47558814      +9.77212275
       332 -294004.41711726     +12.05847089
       333 -293990.35960249     +14.05751477
       334 -293974.55077661     +15.80882587
       335 -293957.22533982     +17.32543679
       336 -293938.16816862     +19.05717120
       337 -293919.06865338     +19.09951524
       338 -293902.92483797     +16.14381541
       339 -293886.93087385     +15.99396412
       340 -293868.34726717     +18.58360668
       341 -293847.42507858     +20.92218859
       342 -293825.78773004     +21.63734854
       343 -293807.03182882     +18.75590122
       344 -293791.03859561     +15.99323321
       345 -293776.56965476     +14.46894085
       346 -293763.13100287     +13.43865189
       347 -293751.90497916     +11.22602370
       348 -293743.27594996      +8.62902920
       349 -293737.00529114      +6.27065882
       350 -293732.24935903      +4.75593211
       351 -293727.07953179      +5.16982724
       352 -293720.64902108      +6.43051072
       353 -293716.12623350      +4.52278758
       354 -293713.31546978      +2.81076372
       355 -293711.42768657      +1.88778321
       356 -293710.14654503      +1.28114154
       357 -293709.25917426      +0.88737077
       358 -293708.63457352      +0.62460074
       359 -293708.19023021      +0.44434331
       360 -293707.86841225      +0.32181795
       361 -293707.53446240      +0.33394985
       362 -293704.40112749      +3.13333492
       363 -293669.35875726     +35.04237023
       364 -293610.05274058     +59.30601668
       365 -293588.39936621     +21.65337437
       366 -293583.29301080      +5.10635541
       367 -293581.93380055      +1.35921024
       368 -293581.42625744      +0.50754312
       369 -293581.16997320      +0.25628424
       370 -293581.01591935      +0.15405385
       371 -293580.91349401      +0.10242534
       372 -293580.83584538      +0.07764863
       373 -293580.75048316      +0.08536222
       374 -293580.57319581      +0.17728735
       375 -293580.08803043      +0.48516538
       376 -293579.10246835      +0.98556208
       377 -293578.05565704      +1.04681131
       378 -293577.48833180      +0.56732524
       379 -293577.29128963      +0.19704217
       380 -293577.23328072      +0.05800892
       381 -293577.21495243      +0.01832829
       382 -293577.20761226      +0.00734017

2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.454831
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.642500
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.425375
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.449599
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.620687
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.486287
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=6 -> mean_max_reach_y=0.482015
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=7 -> mean_max_reach_y=0.587346
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=8 -> mean_max_reach_y=0.785628
2026-03-08 16:14:30 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 8

=== Training HMM with n_states=10 ===

         1 -791807.19248943             +nan
         2 -508678.90395374 +283128.28853570
         3 -430804.27112443  +77874.63282930
         4 -403748.89742984  +27055.37369460
         5 -387081.37828780  +16667.51914204
         6 -380912.01752596   +6169.36076183
         7 -376433.06181737   +4478.95570859
         8 -373049.26399744   +3383.79781993
         9 -370646.24424665   +2403.01975079
        10 -369020.09483232   +1626.14941432
        11 -367667.29458368   +1352.80024865
        12 -366158.19763528   +1509.09694840
        13 -364004.13364685   +2154.06398843
        14 -360827.90624941   +3176.22739743
        15 -355547.89110352   +5280.01514590
        16 -348667.27760182   +6880.61350170
        17 -343225.45259092   +5441.82501090
        18 -339541.09746323   +3684.35512769
        19 -337613.49939196   +1927.59807127
        20 -336606.48916379   +1007.01022817
        21 -336059.81292985    +546.67623393
        22 -335766.58020026    +293.23272959
        23 -335564.73795494    +201.84224532
        24 -335388.14958365    +176.58837129
        25 -335202.79472318    +185.35486046
        26 -335000.50982254    +202.28490064
        27 -334799.92962737    +200.58019517
        28 -334618.39103915    +181.53858823
        29 -334447.65000218    +170.74103696
        30 -334273.30601692    +174.34398527
        31 -334095.82122154    +177.48479537
        32 -333808.25634283    +287.56487871
        33 -333253.05568707    +555.20065576
        34 -332347.95419180    +905.10149527
        35 -331308.30301125   +1039.65118056
        36 -330566.87326735    +741.42974389
        37 -330099.84837569    +467.02489166
        38 -329723.07952073    +376.76885496
        39 -329366.83205215    +356.24746858
        40 -328984.02854698    +382.80350517
        41 -328556.62865591    +427.39989107
        42 -328138.55983432    +418.06882159
        43 -327688.70366791    +449.85616641
        44 -327133.45473106    +555.24893685
        45 -326279.45290186    +854.00182920
        46 -324845.68752201   +1433.76537985
        47 -322670.54643637   +2175.14108564
        48 -320240.75168731   +2429.79474906
        49 -318052.57381134   +2188.17787598
        50 -316251.38497670   +1801.18883464
        51 -314675.78981642   +1575.59516028
        52 -313160.44366710   +1515.34614932
        53 -311596.96270201   +1563.48096509
        54 -309417.04032704   +2179.92237497
        55 -305612.99465237   +3804.04567467
        56 -301333.55330327   +4279.44134910
        57 -299362.07224189   +1971.48106138
        58 -298481.18697737    +880.88526452
        59 -297953.00225033    +528.18472704
        60 -297616.80580851    +336.19644182
        61 -297349.57182555    +267.23398296
        62 -297072.68537428    +276.88645128
        63 -296784.07482996    +288.61054431
        64 -296531.55138637    +252.52344360
        65 -296347.45990501    +184.09148136
        66 -296216.90740741    +130.55249760
        67 -296113.12054767    +103.78685974
        68 -296031.70241893     +81.41812874
        69 -295969.76272333     +61.93969560
        70 -295923.58307348     +46.17964985
        71 -295888.70242904     +34.88064444
        72 -295861.37791717     +27.32451186
        73 -295839.29519000     +22.08272717
        74 -295821.07692548     +18.21826452
        75 -295805.67064029     +15.40628518
        76 -295792.21858508     +13.45205521
        77 -295780.03992570     +12.17865938
        78 -295768.55976907     +11.48015663
        79 -295757.12645018     +11.43331889
        80 -295744.39856104     +12.72788914
        81 -295726.18452662     +18.21403442
        82 -295689.83637797     +36.34814864
        83 -295608.93334383     +80.90303415
        84 -295447.83858937    +161.09475446
        85 -295169.28593305    +278.55265632
        86 -294780.03012476    +389.25580829
        87 -294380.71124048    +399.31888428
        88 -294043.86207943    +336.84916105
        89 -293755.57526025    +288.28681919
        90 -293488.94684051    +266.62841973
        91 -293216.56417397    +272.38266655
        92 -292919.14556598    +297.41860799
        93 -292587.32972452    +331.81584146
        94 -292230.27118094    +357.05854358
        95 -291874.64355756    +355.62762338
        96 -291566.21331109    +308.43024647
        97 -291349.23201540    +216.98129569
        98 -291222.30821724    +126.92379816
        99 -291134.52902280     +87.77919444
       100 -291002.61059680    +131.91842600
       101 -290718.84781831    +283.76277849
       102 -290344.15834870    +374.68946961
       103 -290087.26710838    +256.89124031
       104 -289960.58977367    +126.67733471
       105 -289899.78549363     +60.80428004
       106 -289867.07447478     +32.71101885
       107 -289837.21772439     +29.85675040
       108 -289812.59373880     +24.62398559
       109 -289799.07850314     +13.51523565
       110 -289787.57527775     +11.50322539
       111 -289775.05173408     +12.52354367
       112 -289766.20463841      +8.84709568
       113 -289759.61735998      +6.58727842
       114 -289754.28724186      +5.33011812
       115 -289748.11441509      +6.17282677
       116 -289739.71130243      +8.40311266
       117 -289731.39323067      +8.31807176
       118 -289721.20269168     +10.19053898
       119 -289709.69759768     +11.50509400
       120 -289697.78240958     +11.91518811
       121 -289685.92631062     +11.85609896
       122 -289675.12866762     +10.79764300
       123 -289665.00956044     +10.11910718
       124 -289653.57494556     +11.43461488
       125 -289630.77181589     +22.80312967
       126 -289589.43671378     +41.33510211
       127 -289552.24288130     +37.19383248
       128 -289520.66992919     +31.57295211
       129 -289483.87917903     +36.79075016
       130 -289432.82195708     +51.05722194
       131 -289364.56523824     +68.25671884
       132 -289282.93129799     +81.63394025
       133 -289195.25863693     +87.67266106
       134 -289114.14311844     +81.11551849
       135 -289014.32232338     +99.82079506
       136 -288878.09526563    +136.22705775
       137 -288800.76447150     +77.33079413
       138 -288762.44302012     +38.32145138
       139 -288737.13005653     +25.31296359
       140 -288717.57253531     +19.55752122
       141 -288701.23472741     +16.33780789
       142 -288686.79166088     +14.44306653
       143 -288673.29163773     +13.50002315
       144 -288659.24041655     +14.05122118
       145 -288643.09458780     +16.14582875
       146 -288627.00564264     +16.08894516
       147 -288610.51265940     +16.49298323
       148 -288591.06817876     +19.44448065
       149 -288569.63343733     +21.43474143
       150 -288551.85856216     +17.77487517
       151 -288537.26896757     +14.58959459
       152 -288524.35063971     +12.91832786
       153 -288512.26538165     +12.08525806
       154 -288500.76918963     +11.49619201
       155 -288488.90594425     +11.86324538
       156 -288466.64977322     +22.25617103
       157 -288439.36669584     +27.28307738
       158 -288416.91783263     +22.44886321
       159 -288401.99026140     +14.92757123
       160 -288391.25330922     +10.73695218
       161 -288382.74804976      +8.50525946
       162 -288375.46204236      +7.28600740
       163 -288368.98972670      +6.47231566
       164 -288363.14540040      +5.84432630
       165 -288357.81368206      +5.33171835
       166 -288352.89772569      +4.91595636
       167 -288348.31492293      +4.58280277
       168 -288344.00735478      +4.30756814
       169 -288339.94504679      +4.06230800
       170 -288336.07951193      +3.86553485
       171 -288331.71919720      +4.36031474
       172 -288317.89556983     +13.82362737
       173 -288263.40009356     +54.49547627
       174 -288207.37638004     +56.02371352
       175 -288187.08474753     +20.29163252
       176 -288179.12891193      +7.95583559
       177 -288173.93760529      +5.19130664
       178 -288169.54136138      +4.39624390
       179 -288165.46698112      +4.07438027
       180 -288161.56098786      +3.90599325
       181 -288157.76057691      +3.80041095
       182 -288154.03914238      +3.72143453
       183 -288150.38821925      +3.65092313
       184 -288146.80719430      +3.58102496
       185 -288143.29643047      +3.51076383
       186 -288139.85342939      +3.44300108
       187 -288136.47039195      +3.38303744
       188 -288133.12971643      +3.34067552
       189 -288129.78873403      +3.34098240
       190 -288126.32979022      +3.45894381
       191 -288122.46482170      +3.86496852
       192 -288117.67493013      +4.78989157
       193 -288108.70882809      +8.96610204
       194 -288079.22522590     +29.48360219
       195 -288016.63124207     +62.59398383
       196 -287962.08110976     +54.55013231
       197 -287930.18714903     +31.89396073
       198 -287893.66395238     +36.52319665
       199 -287830.39940786     +63.26454452
       200 -287758.25404132     +72.14536654
       201 -287684.71496373     +73.53907759
       202 -287593.15097627     +91.56398747
       203 -287484.77041837    +108.38055790
       204 -287374.73866428    +110.03175409
       205 -287275.00592780     +99.73273647
       206 -287193.54885540     +81.45707240
       207 -287123.88155183     +69.66730358
       208 -287064.48781347     +59.39373835
       209 -286780.38534196    +284.10247152
       210 -286298.20873528    +482.17660668
       211 -286174.03375435    +124.17498092
       212 -286127.90635453     +46.12739982
       213 -286096.97339395     +30.93296058
       214 -286074.53677840     +22.43661555
       215 -286056.91433678     +17.62244163
       216 -286045.51892520     +11.39541158
       217 -286037.75009606      +7.76882914
       218 -286030.70495897      +7.04513709
       219 -286023.86707977      +6.83787920
       220 -286019.35304107      +4.51403870
       221 -286016.13588374      +3.21715733
       222 -286012.19438327      +3.94150047
       223 -285995.71360041     +16.48078286
       224 -285931.27257918     +64.44102123
       225 -285830.62082813    +100.65175105
       226 -285764.27602291     +66.34480522
       227 -285733.10125775     +31.17476516
       228 -285717.19979154     +15.90146621
       229 -285707.35292559      +9.84686595
       230 -285700.26357542      +7.08935017
       231 -285694.94833235      +5.31524307
       232 -285690.90210610      +4.04622625
       233 -285687.65131801      +3.25078809
       234 -285684.91980428      +2.73151373
       235 -285682.54526817      +2.37453612
       236 -285680.41926845      +2.12599971
       237 -285678.46386201      +1.95540644
       238 -285676.62142467      +1.84243734
       239 -285674.84890703      +1.77251764
       240 -285673.11385821      +1.73504882
       241 -285671.39143734      +1.72242087
       242 -285669.66211576      +1.72932158
       243 -285667.90987461      +1.75224116
       244 -285666.12074935      +1.78912526
       245 -285664.28162827      +1.83912108
       246 -285662.37925879      +1.90236948
       247 -285660.39943807      +1.97982072
       248 -285658.32636514      +2.07307294
       249 -285656.14212532      +2.18423981
       250 -285653.82627499      +2.31585033
       251 -285651.35549511      +2.47077988
       252 -285648.70327774      +2.65221737
       253 -285645.83958108      +2.86369666
       254 -285642.73031302      +3.10926806
       255 -285639.33635837      +3.39395465
       256 -285635.61163671      +3.72472166
       257 -285631.49931159      +4.11232512
       258 -285626.92444187      +4.57486972
       259 -285621.77866257      +5.14577929
       260 -285615.88195344      +5.89670913
       261 -285608.86286347      +7.01908997
       262 -285599.76758919      +9.09527428
       263 -285586.39033726     +13.37725193
       264 -285564.72446997     +21.66586729
       265 -285532.06535039     +32.65911957
       266 -285491.27671039     +40.78864000
       267 -285442.67957278     +48.59713761
       268 -285391.56997764     +51.10959514
       269 -285342.28580823     +49.28416941
       270 -285296.78076496     +45.50504327
       271 -285252.48704466     +44.29372030
       272 -285207.11103625     +45.37600842
       273 -285172.17666314     +34.93437310
       274 -285143.51706330     +28.65959984
       275 -285119.78483767     +23.73222563
       276 -285100.37822081     +19.40661686
       277 -285084.69254369     +15.68567711
       278 -285072.02875441     +12.66378929
       279 -285061.69958966     +10.32916475
       280 -285053.12152481      +8.57806485
       281 -285045.85358574      +7.26793906
       282 -285039.57930023      +6.27428551
       283 -285034.06368269      +5.51561754
       284 -285029.13119420      +4.93248849
       285 -285024.65606710      +4.47512710
       286 -285020.54335438      +4.11271272
       287 -285016.71000934      +3.83334504
       288 -285013.07732691      +3.63268242
       289 -285009.57039896      +3.50692796
       290 -285006.11583362      +3.45456533
       291 -285002.62080456      +3.49502906
       292 -284998.74080041      +3.88000415
       293 -284990.32467116      +8.41612925
       294 -284979.58925719     +10.73541397
       295 -284972.53948468      +7.04977251
       296 -284963.03964569      +9.49983900
       297 -284952.81676019     +10.22288549
       298 -284943.51390819      +9.30285200
       299 -284934.80255569      +8.71135251
       300 -284926.56676935      +8.23578634
       301 -284918.68082973      +7.88593962
       302 -284910.98722499      +7.69360474
       303 -284903.30111245      +7.68611254
       304 -284895.32460037      +7.97651208
       305 -284886.35782667      +8.96677370
       306 -284873.36522598     +12.99260069
       307 -284855.13409739     +18.23112859
       308 -284833.63505769     +21.49903971
       309 -284806.24172712     +27.39333057
       310 -284775.55572753     +30.68599959
       311 -284744.79645647     +30.75927106
       312 -284712.16210671     +32.63434976
       313 -284672.68793895     +39.47416776
       314 -284629.35557417     +43.33236478
       315 -284583.07504983     +46.28052434
       316 -284520.64740645     +62.42764338
       317 -284460.74292379     +59.90448265
       318 -284414.85178483     +45.89113896
       319 -284376.33524463     +38.51654020
       320 -284341.44912204     +34.88612259
       321 -284309.82066255     +31.62845949
       322 -284272.70343990     +37.11722265
       323 -284231.32508026     +41.37835964
       324 -284197.57922872     +33.74585154
       325 -284169.45264152     +28.12658720
       326 -284142.03362426     +27.41901726
       327 -284115.09367646     +26.93994781
       328 -284090.08180685     +25.01186961
       329 -284067.53665487     +22.54515198
       330 -284045.47025279     +22.06640208
       331 -284012.48963475     +32.98061803
       332 -283947.96320752     +64.52642723
       333 -283895.41308821     +52.55011932
       334 -283836.50154414     +58.91154407
       335 -283755.24724574     +81.25429840
       336 -283632.32480103    +122.92244470
       337 -283447.42560480    +184.89919623
       338 -283181.09505029    +266.33055451
       339 -282918.94851246    +262.14653783
       340 -282645.29631709    +273.65219537
       341 -282363.03381707    +282.26250002
       342 -282093.93285089    +269.10096618
       343 -281898.89535854    +195.03749235
       344 -281785.96744914    +112.92790940
       345 -281734.92643823     +51.04101091
       346 -281712.40998727     +22.51645096
       347 -281700.33528795     +12.07469932
       348 -281693.23046663      +7.10482132
       349 -281688.94539904      +4.28506759
       350 -281684.83731132      +4.10808772
       351 -281681.99762600      +2.83968532
       352 -281681.03291426      +0.96471174
       353 -281680.46093256      +0.57198170
       354 -281680.09835914      +0.36257342
       355 -281679.86159887      +0.23676027
       356 -281679.70322277      +0.15837610
       357 -281679.59496417      +0.10825860
       358 -281679.51951651      +0.07544766
       359 -281679.46603333      +0.05348318
       360 -281679.42755667      +0.03847666
       361 -281679.39951988      +0.02803679
       362 -281679.37886110      +0.02065878
       363 -281679.36348782      +0.01537328
       364 -281679.35194598      +0.01154184
       365 -281679.34321060      +0.00873538

2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.631948
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.404875
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.453349
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.606866
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.479632
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.779987
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=6 -> mean_max_reach_y=0.512708
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=7 -> mean_max_reach_y=0.486586
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=8 -> mean_max_reach_y=0.448736
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=9 -> mean_max_reach_y=0.769755
2026-03-08 16:15:57 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 5

=== Training HMM with n_states=11 ===

         1 -735955.63469359             +nan
         2 -459798.79884501 +276156.83584858
         3 -395824.31655451  +63974.48229050
         4 -382284.80174535  +13539.51480916
         5 -374936.04712030   +7348.75462505
         6 -367223.63090759   +7712.41621271
         7 -360785.28230820   +6438.34859940
         8 -355930.49205310   +4854.79025510
         9 -351495.95338023   +4434.53867287
        10 -342873.88267420   +8622.07070603
        11 -332183.05687646  +10690.82579773
        12 -326665.36596283   +5517.69091363
        13 -323673.09544883   +2992.27051399
        14 -320832.41094638   +2840.68450245
        15 -316841.23525318   +3991.17569320
        16 -311013.43293337   +5827.80231981
        17 -305163.62738087   +5849.80555250
        18 -301330.89759089   +3832.72978998
        19 -298110.46476025   +3220.43283063
        20 -295466.49601086   +2643.96874940
        21 -293760.72938566   +1705.76662519
        22 -292681.10254364   +1079.62684202
        23 -291818.88432128    +862.21822236
        24 -291092.34139504    +726.54292624
        25 -290496.16399977    +596.17739527
        26 -289962.30312377    +533.86087600
        27 -289598.45707006    +363.84605371
        28 -289338.06961073    +260.38745933
        29 -289123.80070056    +214.26891017
        30 -288883.85297588    +239.94772468
        31 -288707.05848809    +176.79448779
        32 -288500.57059154    +206.48789655
        33 -288161.17289331    +339.39769824
        34 -287874.77710032    +286.39579298
        35 -287707.82427798    +166.95282234
        36 -287591.75449959    +116.06977838
        37 -287481.74912307    +110.00537652
        38 -287356.59904116    +125.15008191
        39 -287210.35955384    +146.23948732
        40 -287064.93325680    +145.42629704
        41 -286946.35256577    +118.58069103
        42 -286857.33980580     +89.01275997
        43 -286787.81061004     +69.52919576
        44 -286731.86663618     +55.94397386
        45 -286691.46620052     +40.40043566
        46 -286660.52334546     +30.94285506
        47 -286635.47195396     +25.05139150
        48 -286614.17325226     +21.29870170
        49 -286595.39434213     +18.77891013
        50 -286578.56248023     +16.83186190
        51 -286563.45730853     +15.10517170
        52 -286549.80696025     +13.65034827
        53 -286537.18644245     +12.62051781
        54 -286525.33642374     +11.85001871
        55 -286514.37808671     +10.95833703
        56 -286504.74796448      +9.63012222
        57 -286496.93807313      +7.80989135
        58 -286491.14730004      +5.79077309
        59 -286487.13158613      +4.01571391
        60 -286484.38781627      +2.74376986
        61 -286482.44044995      +1.94736632
        62 -286480.97259464      +1.46785531
        63 -286479.80823193      +1.16436271
        64 -286478.85631281      +0.95191913
        65 -286478.06824976      +0.78806304
        66 -286477.40781314      +0.66043662
        67 -286476.70891571      +0.69889743
        68 -286474.36212804      +2.34678767
        69 -286469.03400239      +5.32812565
        70 -286466.37856328      +2.65543911
        71 -286465.65793525      +0.72062803
        72 -286465.27259527      +0.38533998
        73 -286464.99050495      +0.28209032
        74 -286464.76509200      +0.22541295
        75 -286464.57690826      +0.18818374
        76 -286464.41515635      +0.16175191
        77 -286464.27297431      +0.14218205
        78 -286464.14563983      +0.12733448
        79 -286464.02974369      +0.11589614
        80 -286463.92275126      +0.10699244
        81 -286463.82274209      +0.10000916
        82 -286463.72824183      +0.09450027
        83 -286463.63810706      +0.09013476
        84 -286463.55144325      +0.08666381
        85 -286463.46754380      +0.08389945
        86 -286463.38584215      +0.08170165
        87 -286463.30586824      +0.07997391
        88 -286463.22719595      +0.07867228
        89 -286463.14935143      +0.07784452
        90 -286463.07160754      +0.07774389
        91 -286462.99247382      +0.07913372
        92 -286462.90840392      +0.08406990
        93 -286462.81061938      +0.09778454
        94 -286462.67814203      +0.13247735
        95 -286462.46726839      +0.21087364
        96 -286462.11557625      +0.35169215
        97 -286461.60779201      +0.50778424
        98 -286461.05855222      +0.54923979
        99 -286460.61889426      +0.43965795
       100 -286460.32484097      +0.29405330
       101 -286460.11632102      +0.20851995
       102 -286459.89743897      +0.21888205
       103 -286459.56687283      +0.33056614
       104 -286459.15664824      +0.41022458
       105 -286458.84500409      +0.31164415
       106 -286458.65571827      +0.18928582
       107 -286458.52138721      +0.13433107
       108 -286458.40569771      +0.11568950
       109 -286458.29653693      +0.10916078
       110 -286458.19004740      +0.10648953
       111 -286458.08496511      +0.10508229
       112 -286457.98092864      +0.10403646
       113 -286457.87789627      +0.10303237
       114 -286457.77590144      +0.10199483
       115 -286457.67494362      +0.10095782
       116 -286457.57494759      +0.09999603
       117 -286457.47575964      +0.09918795
       118 -286457.37716207      +0.09859757
       119 -286457.27889343      +0.09826864
       120 -286457.18066642      +0.09822701
       121 -286457.08217541      +0.09849101
       122 -286456.98307750      +0.09909790
       123 -286456.88289496      +0.10018254
       124 -286456.78066150      +0.10223346
       125 -286456.67372363      +0.10693787
       126 -286456.55394295      +0.11978068
       127 -286456.39805989      +0.15588306
       128 -286456.16106739      +0.23699249
       129 -286455.84072518      +0.32034222
       130 -286455.56362970      +0.27709548
       131 -286455.38759138      +0.17603832
       132 -286455.25420500      +0.13338638
       133 -286455.12872176      +0.12548324
       134 -286455.00279263      +0.12592913
       135 -286454.87469804      +0.12809458
       136 -286454.74387151      +0.13082653
       137 -286454.60993784      +0.13393368
       138 -286454.47256648      +0.13737136
       139 -286454.33144806      +0.14111842
       140 -286454.18628640      +0.14516166
       141 -286454.03679191      +0.14949449
       142 -286453.88267549      +0.15411642
       143 -286453.72364312      +0.15903238
       144 -286453.55939120      +0.16425192
       145 -286453.38960258      +0.16978862
       146 -286453.21394303      +0.17565954
       147 -286453.03205802      +0.18188501
       148 -286452.84356953      +0.18848849
       149 -286452.64807296      +0.19549657
       150 -286452.44513389      +0.20293907
       151 -286452.23428461      +0.21084928
       152 -286452.01502039      +0.21926422
       153 -286451.78679536      +0.22822503
       154 -286451.54901796      +0.23777740
       155 -286451.30104586      +0.24797211
       156 -286451.04218020      +0.25886566
       157 -286450.77165918      +0.27052102
       158 -286450.48865072      +0.28300845
       159 -286450.19224417      +0.29640655
       160 -286449.88144079      +0.31080338
       161 -286449.55514295      +0.32629784
       162 -286449.21214166      +0.34300129
       163 -286448.85110224      +0.36103941
       164 -286448.47054781      +0.38055444
       165 -286448.06884003      +0.40170777
       166 -286447.64415688      +0.42468315
       167 -286447.19446655      +0.44969033
       168 -286446.71749696      +0.47696959
       169 -286446.21069983      +0.50679713
       170 -286445.67120827      +0.53949156
       171 -286445.09578646      +0.57542181
       172 -286444.48076962      +0.61501684
       173 -286443.82199213      +0.65877749
       174 -286443.11470098      +0.70729115
       175 -286442.35345098      +0.76125001
       176 -286441.53197715      +0.82147383
       177 -286440.64303845      +0.88893869
       178 -286439.67822509      +0.96481336
       179 -286438.62771929      +1.05050580
       180 -286437.47999614      +1.14772314
       181 -286436.22144662      +1.25854953
       182 -286434.83589830      +1.38554832
       183 -286433.30400075      +1.53189755
       184 -286431.60242925      +1.70157150
       185 -286429.70284229      +1.89958696
       186 -286427.57050038      +2.13234191
       187 -286425.16241239      +2.40808799
       188 -286422.42481198      +2.73760041
       189 -286419.28966693      +3.13514505
       190 -286415.66976434      +3.61990259
       191 -286411.45165185      +4.21811249
       192 -286406.48527096      +4.96638089
       193 -286400.56834421      +5.91692675
       194 -286393.42217777      +7.14616644
       195 -286384.65289172      +8.76928605
       196 -286373.68677883     +10.96611289
       197 -286359.65704199     +14.02973684
       198 -286341.19230746     +18.46473453
       199 -286315.98849457     +25.20381289
       200 -286279.85125633     +36.13723824
       201 -286224.27339893     +55.57785740
       202 -286129.24299150     +95.03040744
       203 -285936.82044094    +192.42255055
       204 -285426.58697664    +510.23346431
       205 -283637.35968892   +1789.22728772
       206 -279170.19893986   +4467.16074906
       207 -275146.41747342   +4023.78146644
       208 -273253.40267343   +1893.01479999
       209 -272625.10425755    +628.29841588
       210 -272372.37248151    +252.73177604
       211 -272256.19028942    +116.18219209
       212 -272175.04808867     +81.14220075
       213 -272094.18182429     +80.86626438
       214 -272001.24911623     +92.93270806
       215 -271886.33498903    +114.91412720
       216 -271793.93955838     +92.39543065
       217 -271722.31010229     +71.62945610
       218 -271659.25035517     +63.05974711
       219 -271610.91635022     +48.33400496
       220 -271574.75910374     +36.15724648
       221 -271546.69121752     +28.06788622
       222 -271529.08110811     +17.61010941
       223 -271518.93555700     +10.14555111
       224 -271512.10914353      +6.82641347
       225 -271506.65845194      +5.45069159
       226 -271501.84510368      +4.81334827
       227 -271497.31262526      +4.53247842
       228 -271493.19196401      +4.12066125
       229 -271489.98930407      +3.20265993
       230 -271487.77584087      +2.21346320
       231 -271486.20176315      +1.57407772
       232 -271484.97919025      +1.22257290
       233 -271483.98330811      +0.99588214
       234 -271483.16779462      +0.81551349
       235 -271482.50609309      +0.66170152
       236 -271481.97371760      +0.53237550
       237 -271481.54621535      +0.42750225
       238 -271481.20048698      +0.34572837
       239 -271480.91593902      +0.28454796
       240 -271480.67475263      +0.24118639
       241 -271480.46162429      +0.21312833
       242 -271480.26356692      +0.19805737
       243 -271480.07028475      +0.19328216
       244 -271479.87540860      +0.19487615
       245 -271479.67808188      +0.19732672
       246 -271479.48312876      +0.19495311
       247 -271479.29833515      +0.18479361
       248 -271479.13035966      +0.16797549
       249 -271478.98243218      +0.14792748
       250 -271478.85463482      +0.12779736
       251 -271478.74525741      +0.10937741
       252 -271478.65194503      +0.09331238
       253 -271478.57233193      +0.07961311
       254 -271478.50430262      +0.06802931
       255 -271478.44605856      +0.05824405
       256 -271478.39610188      +0.04995668
       257 -271478.35319175      +0.04291013
       258 -271478.31629761      +0.03689413
       259 -271478.28455804      +0.03173957
       260 -271478.25724744      +0.02731061
       261 -271478.23375011      +0.02349732
       262 -271478.21354040      +0.02020971
       263 -271478.19616737      +0.01737304
       264 -271478.18124288      +0.01492449
       265 -271478.16843216      +0.01281071
       266 -271478.15744615      +0.01098601
       267 -271478.14803508      +0.00941107

2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.743218
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.565740
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.472132
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.767530
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.756545
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.465670
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=6 -> mean_max_reach_y=0.578286
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=7 -> mean_max_reach_y=0.637069
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=8 -> mean_max_reach_y=0.401364
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=9 -> mean_max_reach_y=0.431840
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=10 -> mean_max_reach_y=0.485425
2026-03-08 16:17:14 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 3

=== Training HMM with n_states=12 ===

         1 -712900.75327402             +nan
         2 -448076.26528851 +264824.48798550
         3 -387133.21736073  +60943.04792778
         4 -368844.39112715  +18288.82623358
         5 -358252.36488095  +10592.02624621
         6 -347737.54677964  +10514.81810131
         7 -338256.70995073   +9480.83682891
         8 -330659.77077525   +7596.93917548
         9 -323906.98568712   +6752.78508813
        10 -316349.37065478   +7557.61503234
        11 -308622.23241873   +7727.13823605
        12 -303829.37214812   +4792.86027061
        13 -300879.81101941   +2949.56112871
        14 -298755.59117161   +2124.21984780
        15 -297122.12015811   +1633.47101350
        16 -295710.50858383   +1411.61157428
        17 -294439.04806266   +1271.46052117
        18 -292948.48118885   +1490.56687381
        19 -289553.10052374   +3395.38066511
        20 -284338.11288879   +5214.98763495
        21 -280640.84718860   +3697.26570019
        22 -277623.89036810   +3016.95682051
        23 -275502.31972579   +2121.57064230
        24 -274117.98803670   +1384.33168909
        25 -273118.11645145    +999.87158525
        26 -272350.70090997    +767.41554149
        27 -271737.24692608    +613.45398389
        28 -271254.88496010    +482.36196598
        29 -270804.27831140    +450.60664870
        30 -270355.04449991    +449.23381148
        31 -269866.19385428    +488.85064564
        32 -269325.67049340    +540.52336088
        33 -268850.75519512    +474.91529828
        34 -268408.56199452    +442.19320060
        35 -267977.48745047    +431.07454404
        36 -267646.79673748    +330.69071299
        37 -267409.88798795    +236.90874953
        38 -267242.92569187    +166.96229608
        39 -267126.29378600    +116.63190587
        40 -267030.38100296     +95.91278304
        41 -266924.49676734    +105.88423561
        42 -266804.98741001    +119.50935733
        43 -266685.06351599    +119.92389401
        44 -266574.65617137    +110.40734463
        45 -266480.27897857     +94.37719280
        46 -266396.19616877     +84.08280980
        47 -266317.39347930     +78.80268947
        48 -266244.08600161     +73.30747769
        49 -266175.64454091     +68.44146070
        50 -266114.02888817     +61.61565274
        51 -266068.30334114     +45.72554703
        52 -266036.26143209     +32.04190905
        53 -266012.87114255     +23.39028954
        54 -265996.28305114     +16.58809141
        55 -265985.40998702     +10.87306412
        56 -265978.45748901      +6.95249801
        57 -265974.00017090      +4.45731811
        58 -265971.07816558      +2.92200532
        59 -265966.58556015      +4.49260543
        60 -265904.96400872     +61.62155143
        61 -265758.19338962    +146.77061910
        62 -265710.35237864     +47.84101098
        63 -265700.48968123      +9.86269741
        64 -265697.41829940      +3.07138183
        65 -265696.05198669      +1.36631271
        66 -265695.29542062      +0.75656607
        67 -265694.82121421      +0.47420641
        68 -265694.50691379      +0.31430042
        69 -265694.29309477      +0.21381902
        70 -265694.14396945      +0.14912532
        71 -265694.03664433      +0.10732511
        72 -265693.95671999      +0.07992434
        73 -265693.89526998      +0.06145001
        74 -265693.84670093      +0.04856905
        75 -265693.80739023      +0.03931070
        76 -265693.77487872      +0.03251151
        77 -265693.74740068      +0.02747803
        78 -265693.72359982      +0.02380086
        79 -265693.70233683      +0.02126300
        80 -265693.68252571      +0.01981112
        81 -265693.66294098      +0.01958472
        82 -265693.64191156      +0.02102943
        83 -265693.61674063      +0.02517093
        84 -265693.58253786      +0.03420277
        85 -265693.53003495      +0.05250291
        86 -265693.44302804      +0.08700690
        87 -265693.30264522      +0.14038282
        88 -265693.11435461      +0.18829061
        89 -265692.93088376      +0.18347085
        90 -265692.80014925      +0.13073451
        91 -265692.72242841      +0.07772084
        92 -265692.67851516      +0.04391325
        93 -265692.65296671      +0.02554845
        94 -265692.63702517      +0.01594154
        95 -265692.62623759      +0.01078758
        96 -265692.61839228      +0.00784531

2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Automatische Grasp-State-Erkennung (mean_max_reach_y):
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=0 -> mean_max_reach_y=0.392930
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=1 -> mean_max_reach_y=0.758511
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=2 -> mean_max_reach_y=0.601145
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=3 -> mean_max_reach_y=0.581819
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=4 -> mean_max_reach_y=0.469864
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=5 -> mean_max_reach_y=0.307915
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=6 -> mean_max_reach_y=0.760916
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=7 -> mean_max_reach_y=0.643197
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=8 -> mean_max_reach_y=0.485461
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=9 -> mean_max_reach_y=0.482215
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=10 -> mean_max_reach_y=0.778464
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state |   state=11 -> mean_max_reach_y=0.482846
2026-03-08 16:17:51 | INFO     | handpose.backend.ML.DBSCAN.auto_grasp_state | Erkannter Grasp-State: 10

In [6]:
per_file_results = pd.DataFrame(per_file_rows)
model_summary_all = pd.DataFrame(model_rows)

eligible_models = model_summary_all[
    model_summary_all["precision_grasp_micro"] >= MIN_PRECISION_GRASP_MICRO
].copy()

if eligible_models.empty:
    print(
        f"WARN: No model passes precision gate (precision_grasp_micro >= {MIN_PRECISION_GRASP_MICRO:.2f}). "
        "Falling back to all models for ranking."
    )
    ranking_base = model_summary_all
else:
    print(
        f"Models passing precision gate (precision_grasp_micro >= {MIN_PRECISION_GRASP_MICRO:.2f}): "
        f"{len(eligible_models)}/{len(model_summary_all)}"
    )
    ranking_base = eligible_models

model_summary = ranking_base.sort_values(
    by=RANKING_COLUMNS,
    ascending=RANKING_ASCENDING,
).reset_index(drop=True)

if model_summary.empty:
    raise RuntimeError("No model result available.")

best_model = model_summary.iloc[0]

print(
    f"Best model with precision gate (precision_grasp_micro >= {MIN_PRECISION_GRASP_MICRO:.2f}) "
    f"by {PRIMARY_VALIDATION_METRIC}:"
)
print(best_model[["n_states", "grasp_state", "precision_grasp_micro", "validation_score", "f1_grasp_micro", "balanced_accuracy_micro", "mcc_micro"]])

display(model_summary)
display(per_file_results.sort_values(["n_states", "file_name"]).reset_index(drop=True))

Models passing precision gate (precision_grasp_micro >= 0.90): 7/10
Best model with precision gate (precision_grasp_micro >= 0.90) by recall_grasp_micro:
n_states                          8
grasp_state                       1
precision_grasp_micro      0.967914
validation_score           0.874396
f1_grasp_micro             0.918782
balanced_accuracy_micro    0.930887
mcc_micro                  0.888194
Name: 0, dtype: object

,n_states,grasp_state,files_used_for_grasp_detection,n_frames_total,accuracy_micro,balanced_accuracy_micro,precision_grasp_micro,recall_grasp_micro,f1_grasp_micro,specificity_non_grasp_micro,mcc_micro,tn_micro,fp_micro,fn_micro,tp_micro,f1_grasp_macro,balanced_accuracy_macro,validation_score,validation_score_name
0,8,1,501,2047,0.953102,0.930887,0.967914,0.874396,0.918782,0.987377,0.888194,1408,18,78,543,0.917393,0.930773,0.874396,recall_grasp_micro
1,6,2,501,2047,0.936492,0.918511,0.913997,0.872786,0.892916,0.964236,0.848267,1375,51,79,542,0.891740,0.918986,0.872786,recall_grasp_micro
2,7,2,501,2047,0.947728,0.917030,0.986742,0.838969,0.906876,0.995091,0.876410,1419,7,100,521,0.903783,0.916176,0.838969,recall_grasp_micro
3,11,3,501,2047,0.906204,0.851319,0.971429,0.711755,0.821561,0.990884,0.776892,1413,13,179,442,0.818294,0.849453,0.711755,recall_grasp_micro
4,12,10,501,2047,0.911089,0.854371,0.995485,0.710145,0.828947,0.998597,0.791207,1424,2,180,441,0.821596,0.852653,0.710145,recall_grasp_micro
5,10,5,501,2047,0.903762,0.842294,0.995327,0.685990,0.812202,0.998597,0.773908,1424,2,195,426,0.807024,0.841426,0.685990,recall_grasp_micro
6,9,8,501,2047,0.897899,0.832178,0.997585,0.665056,0.798068,0.999299,0.760348,1425,1,208,413,0.791202,0.829806,0.665056,recall_grasp_micro

,accuracy,balanced_accuracy,precision_grasp,recall_grasp,f1_grasp,specificity_non_grasp,mcc,tn,fp,fn,tp,n_states,grasp_state,file_name,n_frames,files_used_for_grasp_detection,state_means
0,0.970149,0.976047,0.910000,0.989130,0.947917,0.962963,0.928630,234,9,1,91,3,2,recording_20260225_143126.csv,335,501,"{0: 0.4479353650478908, 1: 0.5024482701784585,..."
1,0.961538,0.972973,0.882353,1.000000,0.937500,0.945946,0.913596,210,12,0,90,3,2,recording_20260225_143150.csv,312,501,"{0: 0.4479353650478908, 1: 0.5024482701784585,..."
2,0.924765,0.937440,0.809091,0.967391,0.881188,0.907489,0.833846,206,21,3,89,3,2,recording_20260225_143209.csv,319,501,"{0: 0.4479353650478908, 1: 0.5024482701784585,..."
3,0.870861,0.910138,0.685484,1.000000,0.813397,0.820276,0.749858,178,39,0,85,3,2,recording_20260225_143246.csv,302,501,"{0: 0.4479353650478908, 1: 0.5024482701784585,..."
4,0.948276,0.954772,0.866667,0.970149,0.915493,0.939394,0.881297,155,10,2,65,3,2,recording_20260225_143640.csv,232,501,"{0: 0.4479353650478908, 1: 0.5024482701784585,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,0.855799,0.750000,1.000000,0.500000,0.666667,1.000000,0.644787,227,0,46,46,12,10,recording_20260225_143209.csv,319,501,"{0: 0.39292963549876575, 1: 0.7585105406869779..."
66,0.903974,0.832990,0.982759,0.670588,0.797203,0.995392,0.760312,216,1,28,57,12,10,recording_20260225_143246.csv,302,501,"{0: 0.39292963549876575, 1: 0.7585105406869779..."
67,0.943966,0.902985,1.000000,0.805970,0.892562,1.000000,0.864354,165,0,13,54,12,10,recording_20260225_143640.csv,232,501,"{0: 0.39292963549876575, 1: 0.7585105406869779..."
68,0.925490,0.866197,1.000000,0.732394,0.845528,1.000000,0.814767,184,0,19,52,12,10,recording_20260225_143708.csv,255,501,"{0: 0.39292963549876575, 1: 0.7585105406869779..."
69,0.941781,0.931452,1.000000,0.862903,0.926407,1.000000,0.885217,168,0,17,107,12,10,recording_20260225_143723.csv,292,501,"{0: 0.39292963549876575, 1: 0.7585105406869779..."

In [7]:
# Optional: save result tables
output_dir = ROOT_DIR / "data/05_results/hmm"
output_dir.mkdir(parents=True, exist_ok=True)

model_summary_path = output_dir / "hmm_validation_model_summary.csv"
per_file_path = output_dir / "hmm_validation_per_file.csv"

model_summary.to_csv(model_summary_path, index=False)
per_file_results.to_csv(per_file_path, index=False)

print(f"Saved: {model_summary_path}")
print(f"Saved: {per_file_path}")

Saved: /Users/jole/Studium/HandPose/HandPoseEstimation/data/05_results/hmm/hmm_validation_model_summary.csv
Saved: /Users/jole/Studium/HandPose/HandPoseEstimation/data/05_results/hmm/hmm_validation_per_file.csv